import { Doctor } from "@/features/doctors/types";

export const specialtyOptions = [
  "All specialties",
  "General Practice",
  "Cardiology",
  "Pediatrics",
  "Dermatology",
  "Internal Medicine",
] as const;

export const appointmentTypeOptions = [
  { label: "All types", value: "ALL" },
  { label: "In-person", value: "IN_PERSON" },
  { label: "Telemedicine", value: "TELEMEDICINE" },
] as const;

export const doctors: Doctor[] = [
  {
    id: "dr-sarah-jenkins",
    name: "Dr. Sarah Jenkins",
    specialty: "Cardiology",
    rating: 4.9,
    reviewCount: 128,
    description:
      "Specializing in preventive cardiology and cardiovascular health with over 15 years of clinical practice.",
    languages: ["English", "Spanish"],
    clinic: "Oak Ridge Medical Center",
    location: "London, UK",
    feeRange: { min: 120, max: 200 },
    nextAvailable: "Today, 2:30 PM",
    appointmentTypes: ["IN_PERSON", "TELEMEDICINE"],
    consultationFee: 120,
    durationMinutes: 30,
    avatar: {
      initials: "SJ",
      accentClassName: "from-cyan-100 via-sky-50 to-white",
    },
  },
  {
    id: "dr-marcus-chen",
    name: "Dr. Marcus Chen",
    specialty: "Pediatrics",
    rating: 4.8,
    reviewCount: 94,
    description:
      "Dedicated to compassionate care for children from infancy through adolescence, with a focus on long-term wellness.",
    languages: ["English", "Mandarin", "Cantonese"],
    clinic: "Green Valley Pediatrics",
    location: "London, UK",
    feeRange: { min: 80, max: 150 },
    nextAvailable: "Tomorrow, 9:00 AM",
    appointmentTypes: ["IN_PERSON"],
    consultationFee: 80,
    durationMinutes: 30,
    avatar: {
      initials: "MC",
      accentClassName: "from-sky-100 via-cyan-50 to-white",
    },
  },
  {
    id: "dr-elena-rodriguez",
    name: "Dr. Elena Rodriguez",
    specialty: "Dermatology",
    rating: 5,
    reviewCount: 215,
    description:
      "Board-certified dermatologist specializing in medical and cosmetic skin treatments with patient-first follow-up care.",
    languages: ["English", "Spanish", "Portuguese"],
    clinic: "Skin & Beauty Clinic",
    location: "Downtown",
    feeRange: { min: 150, max: 250 },
    nextAvailable: "Wednesday, Oct 25",
    appointmentTypes: ["IN_PERSON", "TELEMEDICINE"],
    consultationFee: 150,
    durationMinutes: 45,
    avatar: {
      initials: "ER",
      accentClassName: "from-teal-100 via-cyan-50 to-white",
    },
  },
  {
    id: "dr-james-wilson",
    name: "Dr. James Wilson",
    specialty: "Internal Medicine",
    rating: 4.7,
    reviewCount: 82,
    description:
      "Comprehensive primary care focused on adult health management, diagnostics, and sustainable treatment planning.",
    languages: ["English"],
    clinic: "City Health Partners",
    location: "London, UK",
    feeRange: { min: 100, max: 180 },
    nextAvailable: "Today, 4:45 PM",
    appointmentTypes: ["IN_PERSON", "TELEMEDICINE"],
    consultationFee: 100,
    durationMinutes: 30,
    avatar: {
      initials: "JW",
      accentClassName: "from-cyan-100 via-slate-50 to-white",
    },
  },
  {
    id: "dr-aisha-khan",
    name: "Dr. Aisha Khan",
    specialty: "General Practice",
    rating: 4.9,
    reviewCount: 171,
    description:
      "Family physician offering everyday care, preventive checkups, and same-day consultation support for recurring concerns.",
    languages: ["English", "Urdu"],
    clinic: "Riverside Family Clinic",
    location: "Canary Wharf",
    feeRange: { min: 70, max: 120 },
    nextAvailable: "Today, 6:15 PM",
    appointmentTypes: ["IN_PERSON", "TELEMEDICINE"],
    consultationFee: 70,
    durationMinutes: 20,
    avatar: {
      initials: "AK",
      accentClassName: "from-sky-100 via-white to-cyan-50",
    },
  },
  {
    id: "dr-daniel-park",
    name: "Dr. Daniel Park",
    specialty: "Cardiology",
    rating: 4.6,
    reviewCount: 67,
    description:
      "Supports patients managing blood pressure, rhythm issues, and long-term heart-health monitoring with practical guidance.",
    languages: ["English", "Korean"],
    clinic: "Harbor Heart Institute",
    location: "Soho",
    feeRange: { min: 130, max: 210 },
    nextAvailable: "Thursday, 11:15 AM",
    appointmentTypes: ["TELEMEDICINE"],
    consultationFee: 130,
    durationMinutes: 30,
    avatar: {
      initials: "DP",
      accentClassName: "from-cyan-100 via-blue-50 to-white",
    },
  },
  {
    id: "dr-lucy-bennett",
    name: "Dr. Lucy Bennett",
    specialty: "Pediatrics",
    rating: 4.8,
    reviewCount: 143,
    description:
      "Known for calm, parent-friendly pediatric visits covering routine health checks, nutrition, and developmental concerns.",
    languages: ["English", "French"],
    clinic: "Little Oaks Pediatric Hub",
    location: "Westminster",
    feeRange: { min: 90, max: 140 },
    nextAvailable: "Friday, 8:45 AM",
    appointmentTypes: ["IN_PERSON"],
    consultationFee: 90,
    durationMinutes: 25,
    avatar: {
      initials: "LB",
      accentClassName: "from-cyan-50 via-slate-50 to-white",
    },
  },
  {
    id: "dr-noah-turner",
    name: "Dr. Noah Turner",
    specialty: "Internal Medicine",
    rating: 4.7,
    reviewCount: 109,
    description:
      "Adult medicine specialist with a focus on metabolic health, long-term care coordination, and prevention strategies.",
    languages: ["English", "German"],
    clinic: "North Bridge Medical",
    location: "London, UK",
    feeRange: { min: 110, max: 170 },
    nextAvailable: "Monday, 10:30 AM",
    appointmentTypes: ["IN_PERSON", "TELEMEDICINE"],
    consultationFee: 110,
    durationMinutes: 35,
    avatar: {
      initials: "NT",
      accentClassName: "from-teal-100 via-cyan-50 to-white",
    },
  },
];
