"""Provider-neutral LLM integration boundary.

This package is intentionally inactive in Phase 6.6. It defines only
implementation-ready contracts for a future LLM adapter layer, provider-neutral
configuration and generation-budget seams, explicit concrete provider adapters,
and an inactive generation orchestrator. It is not wired into the current chat
runtime, workflow engine, retrieval layer, or prompt builder.
"""

from app.llm.adapters import BaseLLMProviderAdapter
from app.llm.budget import (
    LLMGenerationBudget,
    LLMGenerationBudgetCostPreference,
    LLMGenerationBudgetLatencyPreference,
    LLMGenerationBudgetOverrides,
    LLMGenerationBudgetProfile,
    LLMGenerationBudgetProfileCatalog,
    LLMGenerationBudgetQualityPreference,
    LLMGenerationBudgetReasoningEffort,
    LLMGenerationBudgetTranslator,
    LLMGenerationProfileName,
    build_default_generation_budget_profile_catalog,
)
from app.llm.config import (
    LLMConfiguration,
    LLMConfigurationLoader,
    LLMConfigurationSettings,
    LLMGenerationBudgetEnvironmentOverride,
    LLMGenerationBudgetEnvironmentSettings,
    LLMProviderConfiguration,
    LLMProviderEnvironmentSettings,
    LLMProviderFeatureFlags,
    LLMProviderName,
    get_llm_configuration,
)
from app.llm.interfaces import (
    LLMProvider,
    LLMProviderRegistry,
    LLMRequestTranslator,
    LLMResponseTranslator,
)
from app.llm.models import (
    LLMCitation,
    LLMFinishReason,
    LLMGenerationConstraints,
    LLMGenerationRequest,
    LLMGenerationResponse,
    LLMMessage,
    LLMMessageRole,
    LLMProviderCapabilities,
    LLMProviderDescriptor,
    LLMReasoningConfig,
    LLMReasoningEffort,
    LLMReasoningResult,
    LLMRequestedModality,
    LLMStreamingMetadata,
    LLMStreamingOptions,
    LLMStructuredOutputMode,
    LLMStructuredOutputSchema,
    LLMTokenUsage,
    LLMToolCall,
    LLMToolChoice,
    LLMToolChoiceMode,
    LLMToolDefinition,
)
from app.llm.orchestrator import (
    LLMGenerationOrchestrationRequest,
    LLMGenerationOrchestrationResult,
    LLMGenerationOrchestrator,
)
from app.llm.providers import (
    ClaudeProviderAdapter,
    ConfigurableLLMProviderAdapter,
    GeminiProviderAdapter,
    LLMProviderAdapterFactory,
    LLMProviderTransport,
    OllamaProviderAdapter,
    OpenAIProviderAdapter,
    OpenRouterProviderAdapter,
)
from app.llm.registry import InMemoryLLMProviderRegistry
from app.llm.service import LLMIntegrationService, LLMIntegrationStatus

__all__ = [
    "BaseLLMProviderAdapter",
    "ClaudeProviderAdapter",
    "ConfigurableLLMProviderAdapter",
    "GeminiProviderAdapter",
    "LLMConfiguration",
    "LLMConfigurationLoader",
    "LLMConfigurationSettings",
    "LLMCitation",
    "LLMFinishReason",
    "LLMGenerationBudget",
    "LLMGenerationBudgetCostPreference",
    "LLMGenerationBudgetEnvironmentOverride",
    "LLMGenerationBudgetEnvironmentSettings",
    "LLMGenerationBudgetLatencyPreference",
    "LLMGenerationBudgetOverrides",
    "LLMGenerationBudgetProfile",
    "LLMGenerationBudgetProfileCatalog",
    "LLMGenerationBudgetQualityPreference",
    "LLMGenerationBudgetReasoningEffort",
    "LLMGenerationBudgetTranslator",
    "LLMGenerationConstraints",
    "LLMGenerationOrchestrationRequest",
    "LLMGenerationOrchestrationResult",
    "LLMGenerationOrchestrator",
    "LLMGenerationProfileName",
    "LLMGenerationRequest",
    "LLMGenerationResponse",
    "LLMIntegrationService",
    "LLMIntegrationStatus",
    "LLMMessage",
    "LLMMessageRole",
    "LLMProvider",
    "LLMProviderAdapterFactory",
    "LLMProviderConfiguration",
    "LLMProviderCapabilities",
    "LLMProviderDescriptor",
    "LLMProviderEnvironmentSettings",
    "LLMProviderFeatureFlags",
    "LLMProviderName",
    "LLMProviderRegistry",
    "LLMProviderTransport",
    "LLMReasoningConfig",
    "LLMReasoningEffort",
    "LLMReasoningResult",
    "LLMRequestTranslator",
    "LLMRequestedModality",
    "LLMResponseTranslator",
    "LLMStreamingMetadata",
    "LLMStreamingOptions",
    "LLMStructuredOutputMode",
    "LLMStructuredOutputSchema",
    "LLMTokenUsage",
    "LLMToolCall",
    "LLMToolChoice",
    "LLMToolChoiceMode",
    "LLMToolDefinition",
    "InMemoryLLMProviderRegistry",
    "OllamaProviderAdapter",
    "OpenAIProviderAdapter",
    "OpenRouterProviderAdapter",
    "build_default_generation_budget_profile_catalog",
    "get_llm_configuration",
]
