"""Provider-neutral LLM integration boundary.

This package is intentionally inactive in Phase 7. It defines only
implementation-ready contracts for a future LLM adapter layer, provider-neutral
configuration and generation-budget seams, explicit concrete provider adapters,
an inactive runtime composition root, a runtime activation policy seam, an
execution-policy and runtime-routing seam, a production-readiness operations
seam, an inactive runtime facade, a policy-gated controlled-generation branch,
a provider-neutral runtime-response validator, a provider-neutral runtime-
response eligibility gate, and an inactive generation orchestrator. It is not
wired into the current chat runtime, workflow engine, retrieval layer, or
prompt builder.
"""

from app.llm.adapters import BaseLLMProviderAdapter
from app.llm.activation import (
    LLMActivationDiagnostic,
    LLMActivationSeverity,
    LLMProviderActivationStatus,
    LLMRuntimeActivationEvaluator,
    LLMRuntimeActivationResult,
    LLMRuntimeActivationService,
    LLMRuntimeActivationStatus,
)
from app.llm.budget import (
    LLMGenerationBudget,
    LLMGenerationBudgetCostPreference,
    LLMGenerationBudgetLatencyPreference,
    LLMGenerationBudgetOverrides,
    LLMGenerationBudgetProfile,
    LLMGenerationBudgetProfileCatalog,
    LLMGenerationBudgetQualityPreference,
    LLMGenerationBudgetReasoningEffort,
    LLMGenerationBudgetTranslator,
    LLMGenerationProfileName,
    build_default_generation_budget_profile_catalog,
)
from app.llm.composition import (
    InactiveLLMProviderTransportFactory,
    LLMProviderTransportFactory,
    LLMRuntimeComposition,
    LLMRuntimeCompositionRoot,
)
from app.llm.config import (
    LLMConfiguration,
    LLMConfigurationLoader,
    LLMConfigurationSettings,
    LLMGenerationBudgetEnvironmentOverride,
    LLMGenerationBudgetEnvironmentSettings,
    LLMProviderConfiguration,
    LLMProviderEnvironmentSettings,
    LLMProviderFeatureFlags,
    LLMProviderName,
    LLMRuntimeFeatureFlags,
    get_llm_configuration,
)
from app.llm.execution_policy import (
    AIExecutionActivationSnapshot,
    AIExecutionDecision,
    AIExecutionDiagnostic,
    AIExecutionDiagnosticSeverity,
    AIExecutionFallbackStrategy,
    AIExecutionMode,
    AIExecutionOwner,
    AIExecutionPolicyEvaluator,
    AIExecutionPolicyRequest,
    AIExecutionPolicyResult,
    AIExecutionPolicyService,
)
from app.llm.eligibility import (
    LLMRuntimeResponseEligibilityEvaluator,
    LLMRuntimeResponseEligibilityIssue,
    LLMRuntimeResponseEligibilityRequest,
    LLMRuntimeResponseEligibilityResult,
    LLMRuntimeResponseEligibilityStatus,
)
from app.llm.facade import (
    LLMControlledGenerationRequest,
    LLMControlledGenerationResult,
    LLMControlledGenerationStatus,
    InlineLLMShadowExecutionRunner,
    LLMRuntimeFacade,
    LLMRuntimeFacadeSnapshot,
    LLMShadowExecutionRunner,
    LLMShadowModeDiagnostic,
    LLMShadowModeDispatchResult,
    LLMShadowModeRequest,
    LLMShadowModeStatus,
    ThreadedLLMShadowExecutionRunner,
)
from app.llm.interfaces import (
    LLMProvider,
    LLMProviderRegistry,
    LLMRequestTranslator,
    LLMResponseTranslator,
)
from app.llm.models import (
    LLMCitation,
    LLMFinishReason,
    LLMGenerationConstraints,
    LLMGenerationRequest,
    LLMGenerationResponse,
    LLMMessage,
    LLMMessageRole,
    LLMProviderCapabilities,
    LLMProviderDescriptor,
    LLMReasoningConfig,
    LLMReasoningEffort,
    LLMReasoningResult,
    LLMRequestedModality,
    LLMStreamingMetadata,
    LLMStreamingOptions,
    LLMStructuredOutputMode,
    LLMStructuredOutputSchema,
    LLMTokenUsage,
    LLMToolCall,
    LLMToolChoice,
    LLMToolChoiceMode,
    LLMToolDefinition,
)
from app.llm.operations import (
    LLMAuditTrailRecord,
    LLMAuditVisibility,
    LLMCostAggregationWindow,
    LLMCostBreakdown,
    LLMCostRollup,
    LLMHealthDiagnostic,
    LLMObservabilityPolicy,
    LLMObservabilityRecord,
    LLMOperationalHealthReport,
    LLMOperationalHealthStatus,
    LLMOperationalReadinessEvaluator,
    LLMOperationalReadinessProfile,
    LLMOperationalReadinessResult,
    LLMOperationalReadinessService,
    LLMPerformanceMetrics,
    LLMProviderHealthReport,
    LLMProviderRetryPolicy,
    LLMRetryBackoffStrategy,
    LLMRetryPolicy,
    LLMRolloutPolicy,
    LLMRolloutStage,
    LLMSecurityPrivacyPolicy,
    LLMTimingBreakdown,
    LLMTimeoutPolicy,
    LLMTokenAccounting,
    LLMTraceContext,
)
from app.llm.orchestrator import (
    LLMGenerationOrchestrationRequest,
    LLMGenerationOrchestrationResult,
    LLMGenerationOrchestrator,
)
from app.llm.providers import (
    ClaudeProviderAdapter,
    ConfigurableLLMProviderAdapter,
    GeminiProviderAdapter,
    LLMProviderAdapterFactory,
    LLMProviderTransport,
    OllamaProviderAdapter,
    OpenAIProviderAdapter,
    OpenRouterProviderAdapter,
)
from app.llm.registry import InMemoryLLMProviderRegistry
from app.llm.service import LLMIntegrationService, LLMIntegrationStatus
from app.llm.validation import (
    LLMRuntimeResponseValidationIssue,
    LLMRuntimeResponseValidationRequest,
    LLMRuntimeResponseValidationResult,
    LLMRuntimeResponseValidationStatus,
    LLMRuntimeResponseValidator,
)

__all__ = [
    "AIExecutionActivationSnapshot",
    "AIExecutionDecision",
    "AIExecutionDiagnostic",
    "AIExecutionDiagnosticSeverity",
    "AIExecutionFallbackStrategy",
    "AIExecutionMode",
    "AIExecutionOwner",
    "AIExecutionPolicyEvaluator",
    "AIExecutionPolicyRequest",
    "AIExecutionPolicyResult",
    "AIExecutionPolicyService",
    "BaseLLMProviderAdapter",
    "ClaudeProviderAdapter",
    "ConfigurableLLMProviderAdapter",
    "GeminiProviderAdapter",
    "InactiveLLMProviderTransportFactory",
    "InlineLLMShadowExecutionRunner",
    "LLMActivationDiagnostic",
    "LLMActivationSeverity",
    "LLMConfiguration",
    "LLMConfigurationLoader",
    "LLMConfigurationSettings",
    "LLMControlledGenerationRequest",
    "LLMControlledGenerationResult",
    "LLMControlledGenerationStatus",
    "LLMAuditTrailRecord",
    "LLMAuditVisibility",
    "LLMCitation",
    "LLMCostAggregationWindow",
    "LLMCostBreakdown",
    "LLMCostRollup",
    "LLMFinishReason",
    "LLMGenerationBudget",
    "LLMGenerationBudgetCostPreference",
    "LLMGenerationBudgetEnvironmentOverride",
    "LLMGenerationBudgetEnvironmentSettings",
    "LLMGenerationBudgetLatencyPreference",
    "LLMGenerationBudgetOverrides",
    "LLMGenerationBudgetProfile",
    "LLMGenerationBudgetProfileCatalog",
    "LLMGenerationBudgetQualityPreference",
    "LLMGenerationBudgetReasoningEffort",
    "LLMGenerationBudgetTranslator",
    "LLMGenerationConstraints",
    "LLMGenerationOrchestrationRequest",
    "LLMGenerationOrchestrationResult",
    "LLMGenerationOrchestrator",
    "LLMGenerationProfileName",
    "LLMGenerationRequest",
    "LLMGenerationResponse",
    "LLMIntegrationService",
    "LLMIntegrationStatus",
    "LLMMessage",
    "LLMMessageRole",
    "LLMHealthDiagnostic",
    "LLMObservabilityPolicy",
    "LLMObservabilityRecord",
    "LLMOperationalHealthReport",
    "LLMOperationalHealthStatus",
    "LLMOperationalReadinessEvaluator",
    "LLMOperationalReadinessProfile",
    "LLMOperationalReadinessResult",
    "LLMOperationalReadinessService",
    "LLMPerformanceMetrics",
    "LLMProvider",
    "LLMProviderAdapterFactory",
    "LLMProviderHealthReport",
    "LLMProviderConfiguration",
    "LLMProviderActivationStatus",
    "LLMProviderCapabilities",
    "LLMProviderDescriptor",
    "LLMProviderEnvironmentSettings",
    "LLMProviderFeatureFlags",
    "LLMProviderName",
    "LLMProviderRetryPolicy",
    "LLMProviderRegistry",
    "LLMProviderTransportFactory",
    "LLMProviderTransport",
    "LLMReasoningConfig",
    "LLMReasoningEffort",
    "LLMReasoningResult",
    "LLMRequestTranslator",
    "LLMRequestedModality",
    "LLMRetryBackoffStrategy",
    "LLMRetryPolicy",
    "LLMRolloutPolicy",
    "LLMRolloutStage",
    "LLMResponseTranslator",
    "LLMRuntimeActivationEvaluator",
    "LLMRuntimeActivationResult",
    "LLMRuntimeActivationService",
    "LLMRuntimeActivationStatus",
    "LLMRuntimeResponseEligibilityEvaluator",
    "LLMRuntimeResponseEligibilityIssue",
    "LLMRuntimeResponseEligibilityRequest",
    "LLMRuntimeResponseEligibilityResult",
    "LLMRuntimeResponseEligibilityStatus",
    "LLMRuntimeComposition",
    "LLMRuntimeCompositionRoot",
    "LLMRuntimeFacade",
    "LLMRuntimeFacadeSnapshot",
    "LLMRuntimeResponseValidationIssue",
    "LLMRuntimeResponseValidationRequest",
    "LLMRuntimeResponseValidationResult",
    "LLMRuntimeResponseValidationStatus",
    "LLMRuntimeResponseValidator",
    "LLMShadowExecutionRunner",
    "LLMShadowModeDiagnostic",
    "LLMShadowModeDispatchResult",
    "LLMShadowModeRequest",
    "LLMShadowModeStatus",
    "LLMRuntimeFeatureFlags",
    "LLMSecurityPrivacyPolicy",
    "LLMStreamingMetadata",
    "LLMStreamingOptions",
    "LLMStructuredOutputMode",
    "LLMStructuredOutputSchema",
    "LLMTimingBreakdown",
    "LLMTimeoutPolicy",
    "LLMTokenAccounting",
    "LLMTokenUsage",
    "LLMTraceContext",
    "LLMToolCall",
    "LLMToolChoice",
    "LLMToolChoiceMode",
    "LLMToolDefinition",
    "ThreadedLLMShadowExecutionRunner",
    "InMemoryLLMProviderRegistry",
    "OllamaProviderAdapter",
    "OpenAIProviderAdapter",
    "OpenRouterProviderAdapter",
    "build_default_generation_budget_profile_catalog",
    "get_llm_configuration",
]
